name: SATVocabApp
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.satspell.SATVocabApp
    DEVELOPMENT_TEAM: ""
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"

targets:
  SATVocabApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/SATVocabApp
      - path: Resources/data.db
        buildPhase: resources
      - path: Resources/Images
        type: folder
        buildPhase: resources
    dependencies:
      - sdk: libsqlite3.tbd
    settings:
      base:
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Resources/Info.plist
